#ifndef RTW_HEADER_Auto_microgrid_forecasting_020822_acc_types_h_
#define RTW_HEADER_Auto_microgrid_forecasting_020822_acc_types_h_
#include "rtwtypes.h"
#include "multiword_types.h"
typedef struct P_Subsystempi2delay_Auto_microgrid_forecasting_020822_T_
P_Subsystempi2delay_Auto_microgrid_forecasting_020822_T ; typedef struct
P_Subsystem1_Auto_microgrid_forecasting_020822_T_
P_Subsystem1_Auto_microgrid_forecasting_020822_T ; typedef struct
P_AutomaticGainControl_Auto_microgrid_forecasting_020822_T_
P_AutomaticGainControl_Auto_microgrid_forecasting_020822_T ; typedef struct
P_NegSeqComputation_Auto_microgrid_forecasting_020822_T_
P_NegSeqComputation_Auto_microgrid_forecasting_020822_T ; typedef struct
P_ZeroSeqComputation_Auto_microgrid_forecasting_020822_T_
P_ZeroSeqComputation_Auto_microgrid_forecasting_020822_T ; typedef struct
P_NegSeqComputation_Auto_microgrid_forecasting_020822_i_T_
P_NegSeqComputation_Auto_microgrid_forecasting_020822_i_T ; typedef struct
P_RMS_Auto_microgrid_forecasting_020822_T_
P_RMS_Auto_microgrid_forecasting_020822_T ; typedef struct
P_TrueRMS_Auto_microgrid_forecasting_020822_T_
P_TrueRMS_Auto_microgrid_forecasting_020822_T ; typedef struct
P_NEGATIVEEdge_Auto_microgrid_forecasting_020822_T_
P_NEGATIVEEdge_Auto_microgrid_forecasting_020822_T ; typedef struct
P_POSITIVEEdge_Auto_microgrid_forecasting_020822_T_
P_POSITIVEEdge_Auto_microgrid_forecasting_020822_T ; typedef struct
P_SwitchCaseActionSubsystem_Auto_microgrid_forecasting_020822_T_
P_SwitchCaseActionSubsystem_Auto_microgrid_forecasting_020822_T ; typedef
struct P_SwitchCaseActionSubsystem2_Auto_microgrid_forecasting_020822_T_
P_SwitchCaseActionSubsystem2_Auto_microgrid_forecasting_020822_T ; typedef
struct P_Subsystempi2delay_Auto_microgrid_forecasting_020822_f_T_
P_Subsystempi2delay_Auto_microgrid_forecasting_020822_f_T ; typedef struct
P_Subsystem1_Auto_microgrid_forecasting_020822_n_T_
P_Subsystem1_Auto_microgrid_forecasting_020822_n_T ; typedef struct
P_CounterASTfmax_Auto_microgrid_forecasting_020822_T_
P_CounterASTfmax_Auto_microgrid_forecasting_020822_T ; typedef struct
P_Auto_microgrid_forecasting_020822_T_ P_Auto_microgrid_forecasting_020822_T
;
#endif
